# Generated by Django 4.2.3 on 2023-07-10 21:40

from django.db import migrations, models
import eventAPI.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eventAPI', '0002_alter_ticket_available_quantity_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='available_quantity',
            field=models.PositiveIntegerField(validators=[eventAPI.validators.ticket_available_quantity_validator]),
        ),
    ]
